backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: "static/uploads"
public_folder: "/uploads" 

collections:
  - name: 'products'
    label: 'Products'
    folder: 'products'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Featured Image', name: 'featuredImage', widget: 'image' }
      - { label: 'Ecommerce Image', name: 'ecommerceImage', widget: 'image' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Price', name: 'price', widget: 'number' }
      - { label: 'Code', name: 'code', widget: 'string' }
      - { label: 'Brands', name: 'brands', widget: 'list'}
      - { label: 'About', name: 'about', widget: 'string'}